[package]
name        = "cw-asset"
description = "Helper library for interacting with Cosmos assets (native coins and CW20 tokens)"
version     = "3.1.0"
authors     = ["Larry Engineer <larry@delphidigital.io>"]
edition     = "2021"
license     = "GPL-3.0-or-later"
repository  = "https://github.com/mars-protocol/cw-asset"

[dependencies]
cosmwasm-schema = "1.5.0"
cosmwasm-std    = "1.5.0"
cw20            = "1.1.2"
cw-address-like = "1.0.4"
cw-storage-plus = "1.2.0"
thiserror       = "1.0.56"

[dev-dependencies]
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
